# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_auto_20151213_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='viewerCount',
            new_name='totalViewers',
        ),
    ]
