# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_auto_20151213_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='totalViewers',
            new_name='total_viewers',
        ),
        migrations.AlterIndexTogether(
            name='player',
            index_together=set([('provider', 'channel')]),
        ),
    ]
