# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_auto_20151214_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
