# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_auto_20151214_0020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['order']},
        ),
    ]
